import uniswap from "../public/assets/projects/uniswap_clone.png";
import custom_blinds from "../public/assets/projects/custom_blinds.png";
import lens_protocol from "../public/assets/projects/lens_protocol.png";
import utp from "../public/assets/projects/utp.png";
import utpMain from '../public/assets/projects/UTP/utpTp.png'
import lensMain from '../public/assets/projects/LENS/lensProtocol.png'
import dappExchange from '../public/assets/blogImgs/dappUexchange.gif'
import lens3 from '../public/assets/projects/LENS/lensProtocol3.png'
import image1 from "../public/assets/blogImgs/bootcampAward.png";
import image2 from "../public/assets/blogImgs/youtube.png";
import image3 from "../public/assets/blogImgs/udemy.png";
import image4 from "../public/assets/blogImgs/dappUniversity.jpg";
import image5 from "../public/assets/blogImgs/springboard.png";
import image6 from "../public/assets/blogImgs/Ms/image6.png";
import image7 from "../public/assets/blogImgs/Ms/image8.png";
import image8 from "../public/assets/blogImgs/Ms/image9.png";
import image9 from "../public/assets/blogImgs/Ms/image7.png";
import image10 from "../public/assets/blogImgs/Ms/image10.png";

export const projects = [
  {
    name: "Up The Punx",
    image1: utpMain,
    image2: utp,
    image3: "",
    type: "web3",
    desc: "Up The Punx is a NFT market place where punk genre related art is sold as NFTs. The NFTs are collectables, but also provide access to exclusive video content from the artist. The site also is setup up for a generative NFT drop if artist provides the art. ",
    tech1: "NextJS",
    tech2: "Tailwind CSS",
    tech3: "Truffle / Ganache",
    tech4: "Solidity",
    tech5: "Web3JS",
    tech6: "Chai / Mocha",
    tech7: "Open Zeppelin",
    tech8: "MetaMask",
    bullet1: "ERC-721 Open Zeppelin audited contracts",
    bullet2: "Contract owner can mint ERC-721 tokens through the platform",
    bullet3: "Buy and Sell NFTs on marketplace platform",
    bullet4: "NFT needed to access exclusive content route",
    url: "",
  },
  {
    name: "Lens Protocol Demo",
    image1: lensMain,
    image2: lens_protocol,
    image3: lens3,
    type: "web3",
    desc: "The demo interacts with the blockchain through the lens api, fetching and returning user profiles. Lens is a decentralizes social media. The goal was to test the api, and user profiles, with the intentions into implementing the protocol into Up The Punx Marketplace.",
    tech1: "NextJS",
    tech2: "GraphQL",
    tech3: "Tailwind CSS",
    tech4: "Polygon",
    tech5: "Ethers",
    tech6: "Solidity",
    tech7: "Lens Protocol Contracts",
    tech8: "MetaMask",
    bullet1: "Lens Protocol API",
    bullet2: "GraphQL / URQL",
    bullet3: "Decentralized Social Media",
    bullet4: "Polygon Network",
    bullet5: "",
    url: "",
  },
  {
    name: "Crypto Exchange",
    image1: dappExchange,
    image2: "",
    image3: "",
    type: "web3",
    desc: "ERC-20 token and Crypto Currency Exchange using Test drive development principles to write soldity code. React used for frontend, Redux to manage state, and truffle/ganache used for local blockchain development.",
    tech1: "React",
    tech2: "Redux",
    tech3: "Solidity",
    tech4: "Web3JS",
    tech5: "ERC-20 Standard",
    tech6: "Mocha / Chai",
    tech7: "Truffle",
    tech8: "Ganache",
    bullet1: "ERC-20 Standard / Tested Contract",
    bullet2: "Test Driven Development for creating Solidity Contracts",
    bullet3: "React class based components",
    bullet4: "Redux state management",
    bullet5: "",
    url: "",
  },
  {
    name: "Personal Portfolio",
    image1: "",
    image2: "",
    image3: "",
    type: "web2",
    desc: "My personal portfolio. Full-stack portfolio re-created and re-designed using favorite technologies and learned practices. I added personal blog with commenting capability using graphCMS. Profile is designed for content to be easily updated",
    tech1: "NextJS",
    tech2: "Tailwind CSS",
    tech3: "GraphCMS",
    tech4: "googleMaps API",
    tech5: "graphQL",
    tech6: "React-Carousel",
    tech7: "MomentJS",
    tech8: "Git",
    bullet1: "Thoughtfully designed to highlight skills and content",
    bullet2: "Created with a deadline",
    bullet3: "Git mindfully used to track and save progress",
    bullet4: "Content management system for Blog posts and updates",
    bullet5: "",
    url: "",
  },
  {
    name: "Damage Squad ",
    image1: "",
    image2: "",
    image3: "",
    type: "web2",
    desc: "Comic style themed website designed for Jiu-jitsu content. Front-end design emphasized, and basic photoshop skills used to create logos and edit images. GraphCMS used to manage blog style posts. Ability to easily update content, wether it be video, blog, or substack posts.",
    tech1: "NextJS",
    tech2: "Tailwind CSS",
    tech3: "GraphCMS",
    tech4: "GraphQL",
    tech5: "Photoshop",
    tech6: "Sub-stack",
    tech7: "Youtube API",
    tech8: "Carousel",
    bullet1: "Fun project to play with tailwind CSS for frontend design",
    bullet2: "First time using Tailwind CSS",
    bullet3: "First time using a CMS to manage content",
    bullet4: "First time using graphQL style query language",
    bullet5: "",
    url: "",
  },
  {
    name: "Ecommerce Custom Blinds",
    image1: custom_blinds,
    image2: "",
    image3: "",
    type: "web2",
    desc: "Ecommerce frame work built while working on tour last summer. The concept is a user submits artwork to be tranposed onto blinds. Project is still being worked on to potentially be converted to a web2/web3 hybrid, utilizing NFTs. ",
    tech1: "NextJS",
    tech2: "Tailwind CSS",
    tech3: "Sanity IO",
    tech4: "Stripe API",
    tech5: "Carousel",
    tech6: "Stripe",
    tech7: "Stuff",
    tech8: "Really Complicated",
    bullet1: "Basic Shopping Cart Functionality",
    bullet2: "Utilizes the STRIPE API",
    bullet3: "Sanity IO for Database/Content Management",
    bullet4: "Future features could involve NFTs",
    bullet5: "",
    url: "",
 
  },
  {
    name: "Technique Tracker",
    image1: "",
    image2: "",
    image3: "",
    type: "web2",
    desc: "",
    tech1: "React",
    tech2: "Redux",
    tech3: "NodeJS",
    tech4: "Express Framework",
    tech5: "MongoDB / Mongoose",
    tech6: "Postman API tool",
    tech7: "Material UI",
    tech8: "Bcrypt and Google Oauth",
    bullet1: "MERN STACK",
    bullet2: "React Functional Components, React Hooks",
    bullet3: "Redux State Management",
    bullet4: "Best Authentication / Authorization principles",
    bullet5: "",
    url: "",
  },
  {
    name: "Technique Tracker",
    image1: "",
    image2: "",
    image3: "",
    type: "web2",
    desc: "",
    tech1: "React",
    tech2: "Redux",
    tech3: "NodeJS",
    tech4: "Express Framework",
    tech5: "MongoDB / Mongoose",
    tech6: "Postman API tool",
    tech7: "Material UI",
    tech8: "Bcrypt and Google Oauth",
    bullet1: "MERN STACK",
    bullet2: "React Functional Components, React Hooks",
    bullet3: "Redux State Management",
    bullet4: "Best Authentication / Authorization principles",
    bullet5: "",
    url: "",
  },
  {
    name: "Technique Tracker",
    image1: "",
    image2: "",
    image3: "",
    type: "web2",
    desc: "",
    tech1: "React",
    tech2: "Redux",
    tech3: "NodeJS",
    tech4: "Express Framework",
    tech5: "MongoDB / Mongoose",
    tech6: "Postman API tool",
    tech7: "Material UI",
    tech8: "Bcrypt and Google Oauth",
    bullet1: "MERN STACK",
    bullet2: "React Functional Components, React Hooks",
    bullet3: "Redux State Management",
    bullet4: "Best Authentication / Authorization principles",
    bullet5: "",
    url: "",
  },
];

export const springBoard = {
  image1,
  image2,
  image3,
  image4,
  image5,
  author: "Danny Devage",
  title: "My Software Engineering Journey",
  desc: "My Software Engineering Journey began as MoneyShot's traction started to slow. The cost of maintanance, app updates, and new features began to pile up and I felt frustrated that the lack of resources were impeding on my vision. That frustration was the catalyst that pointing me into the direction of learning how to code. I didn't take a traditional approach, through college, but began exploring the vast amount of free resources the internet had to offer. Feeling empowered and envigorated I journeyed down the rabbit hole.  ",
  date: "September, 20, 2022",
};

export const moneyShot = {
  image6,
  image7,
  image8,
  image9,
  image10,
  author: "Danny Devage",
  title: "MoneyShot Mobile App",
  desc: "MoneyShot was a mobile app designed for bar patrons to buy other bar patrons a drink digitally. The idea came from a neighborhood bar that I used to manage that used a chalk board as a ledger to keep track of drinks that regular customers would buy for other regulars who were not present at the time, but knew would eventually come in for a drink. With zero experience in tech I took the idea from napkin to both IOS store and Android store.",
  date: "August, 16, 2022",
};
